# Generated by Django 4.1.7 on 2023-03-21 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tv_series", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="RolePayments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("salary", models.PositiveSmallIntegerField()),
                ("days_worked", models.PositiveSmallIntegerField()),
                (
                    "TvSerie_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tv_series.tvserie",
                    ),
                ),
                (
                    "actor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tv_series.actor",
                    ),
                ),
            ],
        ),
    ]
