# Generated by Django 4.1.7 on 2023-03-22 09:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tv_series", "0004_rename_actor_id_payment_actor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="actor",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tv_series.actor",
            ),
        ),
    ]
